const char *song_titles[] = {
"1 - Beat It",
"2 - Billie Jean",
"3 - Ice Ice Baby",
"4 - It's Awesome Baby",
"5 - Let's Get It On!",
"6 - Old MacDonald Had a Farm",
"7 - Where the Streets Have No Name",
"8 - YMCA",
"9 - Celebration",
"10 - Men in Black",
"11 - The Way You Make Me Feel",
"12 - Tribal Dance",
"13 - Black or White",
"14 - Dancing Queen",
"15 - She's Like the Wind",
"16 - Hungry Eyes",
"17 - Rock With You",
"18 - I Will Survive",
"19 - She's Out of My Life",
"20 - Stay",
"21 - Bad",
"22 - Play That Funky Music",
"23 - Man in the Mirror",
"24 - The Wheels on the Bus",
"25 - B-I-N-G-O",
"26 - Thriller",
"27 - The Fresh Prince of Bel Air",
"28 - That's the Way (I Like It)",
"29 - The Girl Is Mine",
"30 - In the Still of the Night",
"31 - Remember the Time",
"32 - Don't Stop Til You Get Enough",
"33 - Wanna Be Starting Something",
"34 - Wild Wild West",
"35 - Lollipop",
"36 - Seventh Inning Stretch",
"37 - Funkytown",
"38 - A.M. Radio",
"39 - Devil With a Blue Dress",
"40 - Jock Jam Mega Mix",
"41 - The Chicken Dance",
"42 - Do Your Ears Hang Low",
"43 - Woodchucks" 
};